#!/bin/bash
# Trading Terminal Security Setup Script
# This script generates secure secrets for production deployment

set -e

echo "🔒 Trading Terminal Security Setup"
echo "================================="

# Check if OpenSSL is available
if ! command -v openssl &> /dev/null; then
    echo "❌ OpenSSL not found. Please install OpenSSL first."
    echo "   On Ubuntu/Debian: sudo apt-get install openssl"
    echo "   On CentOS/RHEL: sudo yum install openssl"
    echo "   On macOS: brew install openssl"
    exit 1
fi

# Generate secure secrets
APP_KEY=$(openssl rand -hex 32)
API_KEY_PEPPER=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
SESSION_SECRET=$(openssl rand -hex 32)

# Create .env file if it doesn't exist
if [ ! -f .env ]; then
    if [ -f .sample.env ]; then
        cp .sample.env .env
        echo "✅ Created .env from .sample.env"
    else
        echo "⚠️  No .sample.env found, creating new .env"
        cat > .env << EOF
# Trading Terminal Environment Configuration
# Generated by security setup script on $(date)

# Security Configuration
APP_KEY=${APP_KEY}
API_KEY_PEPPER=${API_KEY_PEPPER}
JWT_SECRET=${JWT_SECRET}
SESSION_SECRET=${SESSION_SECRET}

# Development Settings
NODE_ENV=development
FLASK_HOST_IP=127.0.0.1
FLASK_PORT=5002
FLASK_DEBUG=true

# API Configuration
VITE_API_URL=http://localhost:5002/api/v1
VITE_WEBSOCKET_URL=ws://localhost:8765
VITE_DEBUG=true
VITE_MOCK_DATA=false

# Dhan Configuration
DHAN_CLIENT_ID=2511215707
DHAN_SANDBOX_MODE=true
DHAN_SANDBOX_TOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbkNvbnN1bWVyVHlwZSI6IlNFTEYiLCJwYXJ0bmVySWQiOiIiLCJkaGFuQ2xpZW50SWQiOiIyNTExMjE1NzA3Iiwid2ViaG9va1VybCI6IiIsImlzcyIjoiZGhhbiIsImV4cCI6MTc3MTcyOTAxMDF9.WrYToNSN1sEejjJLeDlSw1C_RRvN-AQPLq8a8enq_wNv1sxzcTHd5DRQT5Be2BBWrZJPCYEthPIqpOymBhJCQQ

# Broker Configuration
BROKER_API_KEY=1100353799:::fc94762c
BROKER_API_SECRET=9d08b90e-8905-40dd-9cd3-1126696ae0c2
BROKER_API_KEY_MARKET=1100353799:::fc94762c
BROKER_API_SECRET_MARKET=9d08b90e-8905-40dd-9cd3-1126696ae0c2

# Security Settings
CSRF_ENABLED=false
CORS_ENABLED=true
CORS_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
CORS_ALLOWED_METHODS=GET,POST,DELETE,PUT,PATCH
CORS_ALLOWED_HEADERS=Content-Type,Authorization,X-Requested-With
CORS_ALLOW_CREDENTIALS=false
CORS_MAX_AGE=86400

# CSP Settings
CSP_ENABLED=true
CSP_REPORT_ONLY=false
CSP_DEFAULT_SRC='self'
CSP_SCRIPT_SRC='self'
CSP_STYLE_SRC='self' 'unsafe-inline'
CSP_IMG_SRC='self' data:
CSP_CONNECT_SRC='self' ws: wss:
CSP_FONT_SRC='self'
CSP_OBJECT_SRC='none'
CSP_MEDIA_SRC='self'
CSP_FRAME_SRC='none'
CSP_FORM_ACTION='self'
CSP_FRAME_ANCESTORS='self'
CSP_BASE_URI='self'
CSP_UPGRADE_INSECURE_REQUESTS=false
EOF
    fi
else
    echo "📁 .env file already exists, backing up..."
    cp .env .env.backup.$(date +%Y%m%d_%H%M%S)
fi

# Update .env with secure secrets (only if they don't exist)
if ! grep -q "^APP_KEY=" .env; then
    echo "APP_KEY=${APP_KEY}" >> .env
fi
if ! grep -q "^API_KEY_PEPPER=" .env; then
    echo "API_KEY_PEPPER=${API_KEY_PEPPER}" >> .env
fi
if ! grep -q "^JWT_SECRET=" .env; then
    echo "JWT_SECRET=${JWT_SECRET}" >> .env
fi
if ! grep -q "^SESSION_SECRET=" .env; then
    echo "SESSION_SECRET=${SESSION_SECRET}" >> .env
fi

# Set secure file permissions
chmod 600 .env
if [ -f .env.backup.* ]; then
    chmod 600 .env.backup.*
fi

# Create scripts directory if it doesn't exist
if [ ! -d scripts ]; then
    mkdir -p scripts
    echo "📁 Created scripts directory"
fi

# Create startup security check script
cat > scripts/security-check.js << 'EOF'
// Startup Security Check
const SecurityConfig = require('../utils/security-config');

function checkSecurityOnStartup() {
  const errors = SecurityConfig.checkProductionSecurity();
  
  if (errors.length > 0) {
    console.error('🚨 SECURITY ISSUES DETECTED:');
    errors.forEach(error => console.error(\`   - \${error}\`));
    
    if (process.env.NODE_ENV === 'production') {
      console.error('\\n❌ Cannot start in production with security issues');
      process.exit(1);
    } else {
      console.warn('\\n⚠️  Running in development mode with security issues');
    }
  } else {
    console.log('✅ Security checks passed');
  }
}

module.exports = { checkSecurityOnStartup };
EOF

chmod 755 scripts/security-check.js

# Create installation script for security dependencies
cat > scripts/install-security.sh << 'EOF'
#!/bin/bash
echo "📦 Installing security dependencies..."
npm install helmet express-rate-limit express-validator dotenv
echo "✅ Security dependencies installed"
EOF

chmod 755 scripts/install-security.sh

# Create audit script
cat > scripts/security-audit.sh << 'EOF'
#!/bin/bash
echo "🔍 Running security audit..."
npm audit
echo "🔍 Running dependency check..."
npm ls --depth=0
echo "✅ Security audit complete"
EOF

chmod 755 scripts/security-audit.sh

echo "✅ Security configuration complete!"
echo "🔑 Generated secure secrets:"
echo "   - APP_KEY: ${APP_KEY:0:16}..."
echo "   - API_KEY_PEPPER: ${API_KEY_PEPPER:0:16}..."
echo "   - JWT_SECRET: ${JWT_SECRET:0:16}..."
echo "   - SESSION_SECRET: ${SESSION_SECRET:0:16}..."
echo ""
echo "⚠️  IMPORTANT: Save these secrets in a secure location!"
echo "📁 Backup .env file to secure storage"
echo "🔒 Never commit secrets to version control"
echo ""
echo "📋 Next steps:"
echo "   1. Run: npm run install-security"
echo "   2. Run: npm run security-check"
echo "   3. Run: npm test"
echo "   4. Run: npm run audit"
echo ""
echo "🚀 Your trading terminal is now secure!"
